splash = false

wallpaper {
    monitor = DP-4
    path = ~/Pictures/wallpaper/1-city-view.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = ~/Pictures/wallpaper/1-city-view.png
    fit_mode = cover
}